# Example of everything at once.
modules:
  - bukkit
  - bungee
  - logic
  - console
  - discord:
      bots:
        - bot-name: TOKEN
  - file
  - luckperms
  - replacement
  - sponge
  - vault
pipes:
  - common-demo: # This module is always loaded
    - pass-item: null # This just passes the string on
    - null-item: null # This sets the string to nothing
  - bukkit-demo:
    - bukkit-input: # All of these are optional
      - chat
      - leave
      - join
      - server
      - checkCanceled
      - new-join
      - cancel-chat
    - bukkit-playerlist:
        format: "```\nOnline players (%NUM_PLAYERS%/%MAX_PLAYERS%):\n" # Optional
        format-player: "%PLAYER_NAME%" # Optional
        format-no-players: "**No online players**" # Optional
        trigger-word: "playerlist" # Optional
        ignore-case: "true" # Optional
    - bukkit-output:
        permission: null # Optional
    - bukkit-command:
        args: # optional
          - subcommand-1
        command: "example-command"
        permission: "example-permission"
        format: "/%COMMAND% %ARGS%"
  - bungee-demo:
    - bungee-to:
        channel: "custom-channel"
    - bungee-from:
        channel: "custom-channel"
    - bungee-playerlist:
        format: "```\nOnline players (%NUM_PLAYERS%/%MAX_PLAYERS%):\n" # Optional
        format-player: "%PLAYER_NAME%" # Optional
        format-server: "%SERVER_NAME%" # Optional
        format-no-players: "**No online players**" # Optional
        trigger-word: "playerlist" # Optional
        ignore-case: "true" # Optional
        split-by-server: "false" # Optional
    - bungee-command:
        args: # optional
            - subcommand-1
        command: "example-command"
        permission: "example-permission"
        format: "/%COMMAND% %ARGS%"
    - bungee-output: null
    - bungee-input: # All Optional
        chat: "true"
        disconnect: "true"
        switch-servers: "true"
        join: "true"
        format-chat: "[%SERVER_NAME%] %PLAYER_NAME%: %CHAT_MESSAGE%"
        format-disconnect: "&0[&4<-&0] &e%PLAYER_NAME% has left the network from %PLAYER_SERVER_NAME%, Have a good day!"
        format-switch-servers: "&0[&e<->&0] &e%PLAYER_NAME% has switched to %PLAYER_SERVER_NAME%"
        format-join: "&0[&2->&0] &e%PLAYER_NAME% joined the network on %PLAYER_SERVER_NAME%!"
  - logic-demo:
    - if-contains:
        true: # this can be any list of items
            - pass-item: null
            - null-item: null
        false: null # Or this can be nothing
    - if-equals:
        true: null
        false: null
        equals: "String"
    - if-regex-match:
        true: null
        false: null
        match: "[sS]tring"
    - split:
      - stream-1:
        - pass-item: null
        - pass-item: null
      - stream-2:
        - null-item: null
  - console-demo:
    - console-output: null
    - console-output-error: null
  - discord-demo:
    - discord-input:
        channel: "0" # CHANNEL_ID
        bot: bot-name
    - discord-resolve:
        server: "0" # SERVER_ID
        bot: bot-name
        to-discord: false
        to-plain: true
    - discord-output:
        channel: "0" # CHANNEL_ID
        format: "[%DISCORD_ROLE%]%DISCORD_AUTHOR_NICK_NAME%: %DISCORD_MESSAGE%" # Optional
        bot: bot-name
  - file-demo:
    - file-input:
        path: PATH_TO_FIFO
        delay: 500 # optional, defaults to 500
    - file-output:
        path: PATH_TO_FIFO
        delay: 500 # optional, defaults to 500
  - luckperms-demo:
    - luckperms-context: null  # This loads the PREFIX, SUFFIX and GROUP of the player in the PLAYER_NAME context.
  - replacement-demo:
    - regex:
      - "Regex to find": "regex to replace"
      - "Regex to find": "regex to replace"
    - remove-colors: null
  - sponge-demo:
    - sponge-input: # All of these are optional
      - chat
      - leave
      - join
      - server
      - checkCanceled
    - sponge-playerlist:
        format: "```\nOnline players (%NUM_PLAYERS%/%MAX_PLAYERS%):\n" # Optional
        format-player: "%PLAYER_NAME%" # Optional
        format-no-players: "**No online players**" # Optional
        trigger-word: "playerlist" # Optional
        ignore-case: "true" # Optional
    - sponge-output:
        permission: null # Optional
        sender: "FakeME" # Optional
  - vault-demo:
    - vault-context: null  # This loads the PREFIX, SUFFIX, BALANCE and GROUP of the player in the PLAYER_NAME context.