# Example of everything at once.
modules:
  - bukkit
  - bungee
  - logic
  - console
  - discord:
      bots:
        - bot-name: TOKEN
  - file
#  - luckperms
  - replacement
#  - sponge
#  - vault
pipes:
  - common-demo: # This module is always loaded
    - pass-item: null # This just passes the string on
    - null-item: null # This sets the string to nothing
  - bukkit-demo:
    - bukkit-input: # All of these are optional
      - chat
      - leave
      - join
      - server
      - checkCanceled
    - bukkit-playerlist: null
    - bukkit-output:
        permission: null
    - bukkit-command:
        args: # optional
          - subcommand-1
        command: "example-command"
        permission: "example-permission"
        format: "/%COMMAND% %ARGS%"
  - bungee-demo:
    - bungee-to:
        channel: "custom-channel"
    - bungee-from:
        channel: "custom-channel"
    - bungee-playerlist: null
    - bungee-command:
        args: # optional
            - subcommand-1
        command: "example-command"
        permission: "example-permission"
        format: "/%COMMAND% %ARGS%"
  - logic-demo:
    - if-contains:
        true: # this can be any list of items
            - pass-item: null
            - null-item: null
        false: null # Or this can be nothing
    - if-equals:
        true: null
        false: null
        equals: "String"
    - if-regex-match:
        true: null
        false: null
        match: "[sS]tring"
    - split:
      - stream-1:
        - pass-item: null
        - pass-item: null
      - stream-2:
        - null-item: null
  - console-demo:
    - console-output: null
    - console-output-error: null
  - discord-demo:
    - discord-input:
        channel: "0" # CHANNEL_ID
        bot: bot-name
    - discord-resolve:
        server: "0" # SERVER_ID
        bot: bot-name
        to-discord: false
        to-plain: true
    - discord-output:
        channel: "0" # CHANNEL_ID
        bot: bot-name
  - file-demo:
    - file-input:
        path: PATH_TO_FIFO
        delay: 500 # optional, defaults to 500
    - file-output:
        path: PATH_TO_FIFO
        delay: 500 # optional, defaults to 500
  - luckperms-demo: null
  - replacement-demo:
    - regex:
      - "Regex to find": "regex to replace"
      - "Regex to find": "regex to replace"
    - remove-colors: null
  - sponge-demo: null
  - vault-demo: null