main: com.blalp.chatdirector.ChatDirectorBukkit
version: 0.2.0-alpha-1
name: ChatDirector
softdepend: [Vault, LuckPerms, PlaceholderAPI]
load: POSTWORLD
author: blalp
permissions:
  chatdirector.reload:
    description: "Allows reloading of chatdirector"
commands:
  chatdirectorlocal:
    permission: chatdirector.reload
    description: "Allows reloading of chatdirector"
